// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ConnectedPlayer: newConnectedPlayer(db, opts...),
		Room:            newRoom(db, opts...),
		SchemaMigration: newSchemaMigration(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ConnectedPlayer connectedPlayer
	Room            room
	SchemaMigration schemaMigration
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ConnectedPlayer: q.ConnectedPlayer.clone(db),
		Room:            q.Room.clone(db),
		SchemaMigration: q.SchemaMigration.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ConnectedPlayer: q.ConnectedPlayer.replaceDB(db),
		Room:            q.Room.replaceDB(db),
		SchemaMigration: q.SchemaMigration.replaceDB(db),
	}
}

type queryCtx struct {
	ConnectedPlayer *connectedPlayerDo
	Room            *roomDo
	SchemaMigration *schemaMigrationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ConnectedPlayer: q.ConnectedPlayer.WithContext(ctx),
		Room:            q.Room.WithContext(ctx),
		SchemaMigration: q.SchemaMigration.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
