services:
  postgres:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
      - .docker/postgres/init.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ari

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml",""]
    volumes:
      - .docker/metric/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  backend:
    build:
      context: .docker/app
      dockerfile: local.Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      - DATABASE_HOST=postgres
    depends_on:
      - otel-collector
  