# example 

# build-create-room:
# 	docker build -t ai-phone -f .docker/create_room/Dockerfile .
# 	docker tag ai-phone:latest 373134068305.dkr.ecr.ap-northeast-1.amazonaws.com/ai-phone:latest

# push-create-room: build-create-room
# 	docker push 373134068305.dkr.ecr.ap-northeast-1.amazonaws.com/ai-phone:latest

# run-create-room: build-create-room
# 	docker run -p 8080:8080 373134068305.dkr.ecr.ap-northeast-1.amazonaws.com/ai-phone:latest