// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConnectedPlayer = "connected_player"

// ConnectedPlayer mapped from table <connected_player>
type ConnectedPlayer struct {
	ConnectionID string `gorm:"column:connection_id;primaryKey" json:"connection_id"`
	RoomID       string `gorm:"column:room_id;not null" json:"room_id"`
	Index        int32  `gorm:"column:index;not null" json:"index"`
	Username     string `gorm:"column:username;not null" json:"username"`
}

// TableName ConnectedPlayer's table name
func (*ConnectedPlayer) TableName() string {
	return TableNameConnectedPlayer
}
