// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConnectedPlayer = "connected_players"

// ConnectedPlayer mapped from table <connected_players>
type ConnectedPlayer struct {
	RoomID       string `gorm:"column:room_id;not null" json:"room_id"`
	ConnectionID string `gorm:"column:connection_id;not null" json:"connection_id"`
	PlayerIndex  int32  `gorm:"column:player_index;not null" json:"player_index"`
	Username     string `gorm:"column:username;not null" json:"username"`
}

// TableName ConnectedPlayer's table name
func (*ConnectedPlayer) TableName() string {
	return TableNameConnectedPlayer
}
