// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoom = "rooms"

// Room mapped from table <rooms>
type Room struct {
	RoomID      string `gorm:"column:room_id;primaryKey" json:"room_id"`
	ExtraPrompt string `gorm:"column:extra_prompt" json:"extra_prompt"`
	IsStarted   bool   `gorm:"column:is_started;not null" json:"is_started"`
	GameSize    int32  `gorm:"column:game_size;not null" json:"game_size"`
	CurrentGame int32  `gorm:"column:current_game;not null" json:"current_game"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
