// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	SessionID string    `gorm:"column:session_id;primaryKey" json:"session_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	UserAgent string    `gorm:"column:user_agent;not null" json:"user_agent"`
	CraetedAt time.Time `gorm:"column:craeted_at;not null" json:"craeted_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
